: dup 0 pick ;
: over 1 pick ;
: < swap > ;
: <= > not ;
: >= < not ;
: 1+ 1 + ;
: 1- 1 - ;
: upto { rot rot over over <= } { rot dup 3 pick swap call rot 1+ rot rot } while drop drop drop ;
: do dup call while ;
: p print ;
: print-stack sbase sp { @ print } upto ;
: / divmod drop ;
: % divmod swap drop ;
: wordsize 4 ;
: s:depth sp sbase - wordsize / ;
: s:each sbase sp 8 - rot { rot rot over over < } { rot dup 3 pick swap call rot wordsize + rot rot } while drop drop drop ;
: s:print { @ print } s:each ;
( : pick 2 + wordsize * sp swap - @ ; )
: eq over over < { drop drop 0 } { > { 0 } { 1 } if } if ;
: <> eq not ;
